import "./globals.css";
import TopMenu from "@/components/TopMenu";
import type { Metadata } from "next";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ReduxProvider from "@/redux/ReduxProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="en">
            {/* <body className={inter.className}>{children}</body> */}
            <TopMenu />
            <body>
                <ReduxProvider>
                    <NextAuthProvider session={session}>
                        <TopMenu />
                        {children}
                    </NextAuthProvider>
                </ReduxProvider>
            </body>
        </html>
    );
}
